config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get '/search' => 'posts#search', :as => 'search_page'
  root :to => 'posts#index'
  resources  :users do
    resources :posts, only: [:index]
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :photo
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user?(user)
        user == current_user
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :create, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authenticate_user!
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search 
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else 
      @parameter = params[:search].downcase  
      @results = Post.all.where("lower(title) LIKE :search OR lower(body) LIKE :search", search: @parameter) 
    end  
  end

  def correct_user
    @post = Post.find_by(id: params[:id])
    unless current_user?(@post.user)
      redirect_to user_path(current_user)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :photo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def posts
        @posts = @current_user.posts
    end

    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user?(user)
        user == current_user
    end    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/posts">Coolest Image Pool</a>
    </div>
    <ul class="nav navbar-nav">
        <li class="active"><a href="/posts">Home</a></li>
    </ul>
    <%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
    <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div> 
    </div>  
    <% end %>

    <p class="navbar-text navbar-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imagerepo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render '/layouts/header' %>
  <div class="container">
    <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
    </body>
  </div>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.file_field :photo %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style>
  table, th, td {
    padding: 10px;
  }
</style>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="container">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class="add-padding">
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= image_tag(post.photo, width: 300) if post.photo.attached? %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="container">

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<h3>Search Result</h3>  

    <% @results.each do |result| %>  
        <%= result.title %><br>  
        <%= result.body %><br>
        <%= image_tag(result.photo, width: 300) if result.photo.attached? %>
    <% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= image_tag(@post.photo, width: 400) if @post.photo.attached? %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/posts.html.erb
<style>
  table, th, td {
    padding: 10px;
  }
</style>

<h1>Posts</h1>
<div class="container">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @current_user.posts.each do |post| %>
      <tr class="add-padding">
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.user.email %></td>
        <td><%= image_tag(post.photo, width: 300) if post.photo.attached? %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user?(post.user) %>
          <td><%= link_to "Edit", edit_post_path(post) %></td>
          <td><%= link_to "Delete", post, method: :delete, data: { confirm: "Do you want to delete this post ?"}%></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="container">

<br>

<%= link_to 'New Post', new_post_path %>